### PR TITLE
api report json support 400 404 statuscode

### PR DESCRIPTION
**Pull request by magaofei**
### What was a problem?

```
add 400 and 404 status codes for Generate PDF Report API and Generate JSON Report API
```

### How this PR fixes the problem?

```
==
when i input a error parameter for scan_type , like "fefr" , it return `[ERROR] local variable 'context' referenced before assignment`
```

### Check lists (check `x` in `[ ]` of list items)

- [x] Run MobSF unit tests
- [ ] Tested Working on Linux, Mac, and Windows
- [x] Coding style (indentation, etc)

### Additional Comments (if any)

```
DESCRIBE HERE
```

### CODE REVIEW

**Comment by ajinabraham** [comment]
@magaofei Could you please resolve conflicts?

**Comment by magaofei** [comment]
@ajinabraham ok

**Comment by magaofei** [comment]
And i want to rewrite some code of `MobSF.rest_api.py` , there are a lot of `IF_ELSE` statement, for example, you can use django form. Do you agree? I can try

**Comment by ajinabraham** [comment]
Yes I agree. it needs code refactoring.
```
python -c "import this" | grep nest
Flat is better than nested.
```
👍

**Comment by magaofei** [comment]
OK, i got it.

**Comment by ajinabraham** [comment]
@magaofei Does it add too much value than the existing implementation? If not lets stick with the existing setup and avoid extra dependencies.

**Comment by magaofei** [comment]
@ajinabraham ok

**Pull request merged**
