### PR TITLE
set timeout to 3sec

### PR DESCRIPTION
**Pull request by superpoussin22**
### Describe the Pull Request

```
increase timeoput to 3 sec for slow internet connection 
For malware db it's in another PR 
```

### Checklist for PR

- [X] Run MobSF unit tests (http://your-mobsf-@ip:8000/tests/ or python3 manage.py test).
- [X] Tested Working on Linux, Mac, Windows, and Docker
- [X] Make sure build is passing on your PR. [Build Status](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/pull_requests)
- [X] Coding style (indentation, etc)

### Additional Comments (if any)

```
take a look on #981 
```

### CODE REVIEW

**Comment by magaofei** [comment]
No, the waiting time cannot be too long, it should be reduced, it should not be increased.

**Comment by superpoussin22** [comment]
@magaofei what would be the correct value ? we have some timeout set to 3sec and other to 5s

**Comment by magaofei** [comment]
> @magaofei what would be the correct value ? we have some timeout set to 3sec and other to 5s

2~3sec

**Comment by ajinabraham** [comment]
Not a good idea. We don't want a time out that long.

**Comment by ajinabraham** [comment]
@magaofei Do you have issue with 5 sec timeouts?

**Pull request closed without merging**
