### PR TITLE
change request method decorator param to str

### PR DESCRIPTION
**Pull request by magaofei**
### What was a problem?

```
Request method does not need to support multiple
```

### How this PR fixes the problem?

```
DESCRIBE HERE
```

### Check lists (check `x` in `[ ]` of list items)

- [x] Run MobSF unit tests (http://your-mobsf-@ip:8000/tests/ or python3 manage.py test)
- [x] Tested Working on Linux, Mac, and Windows
- [x] Coding style (indentation, etc)

### Additional Comments (if any)

```
DESCRIBE HERE
```

### CODE REVIEW

**Comment by ajinabraham** [comment]
@magaofei Why string?
In future if we want to support multiple HTTP verbs to a single API string won't be sufficient.

**Comment by magaofei** [comment]
support multiple HTTP verbs ? Doesn't seem to need it?

**Comment by ajinabraham** [comment]
@magaofei Not now, but in future if we need. Then tuples or lists are useful to support multiple verbs. What is the problem you see with lists now?

**Comment by magaofei** [comment]
I have no problem, we can keep it.

**Pull request closed without merging**
