### PR TITLE
support recent scans api

### PR DESCRIPTION
**Pull request by magaofei**
implement #888 
### Describe the Pull Request

```

DESCRIBE THE DETAILS OF PULL REQUEST HERE
```

### Checklist for PR

- [x] Run MobSF unit tests (http://your-mobsf-@ip:8000/tests/ or python3 manage.py test).
- [x] Tested Working on Linux, Mac, Windows, and Docker
- [x] Make sure build is passing on your PR. [Build Status](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/pull_requests)
- [x] Coding style (indentation, etc)

### Additional Comments (if any)

```
DESCRIBE HERE
```

### CODE REVIEW

**Comment by ajinabraham** [comment]
@magaofei Added some minute refactoring

**Comment by ajinabraham** [comment]
Also fixes: https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/842

**Comment by superpoussin22** [comment]
> @magaofei Good to merge once tests are added

good catch I missed to check the automated tests :(

**Comment by ajinabraham** [comment]
Added tests and refactored tests.

**Pull request merged**
