### PR TITLE
[WIP] refactor jadx integration'

### PR DESCRIPTION
**Pull request by superpoussin22**
### Describe the Pull Request

```
Jadx latest version is downloaded and installed at setup level ( jadx source are no more in the MobSG git )

Windows Sript is  adapted  but needs to be tested ( Need to find a laptop with windows )
```

### Checklist for PR

- [X] Run MobSF unit tests and lint `tox -e lint,test`
- [X] Tested Working on Linux, Mac, and Docker
- [X] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [X] Make sure tests are passing on your PR [MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

### Additional Comments (if any)

```
 we could have a script to update only jadx if needed or update the documentation to explain how to upgrade jadx
```

### CODE REVIEW

**Review by ajinabraham — COMMENTED** [review]
@superpoussin22 Ain't using `git submodules` a better approach?
This should give us cross platform support, we don't have to add a new python package and or worry about unzip utility being present.

In future, to update jadx,
Simply do
```
cd mobsf/StaticAnalyzer/tools/jadx
git checkout tags/v1.3.X
cd ..
git add jadx
git commit -m "Updating Jadx to 1.3.X"
```
TODO: Support git submodule update from `setup.py` for pip based installs.

**Comment by superpoussin22** [comment]
@ajinabraham :  if we use submodule, we will clone the code, so we will need to compile it to produce the binaries on each platform with graddle :( or do I miss something ?

**Comment by ajinabraham** [comment]
Oh you are right! They don't have the binaries 😮‍💨  I will revert my changes.

**Comment by Heufiih** [comment]
Hi

**Comment by superpoussin22** [comment]
@ajinabraham if we go like this  the automated tests need also to  install jadx or all will fail

**Comment by ajinabraham** [comment]
@superpoussin22 What happens if we run setup twice? Will it overwrite jadx or fail?

**Comment by superpoussin22** [comment]
> @superpoussin22 What happens if we run setup twice? Will it overwrite jadx or fail at the unzip step?

good question let me check again

**Comment by superpoussin22** [comment]
> @ajinabraham 

if we stay like this it does nothin but unzip will fail, unless I add a check , or I can force to download it again as you want

**Comment by ajinabraham** [comment]
Maybe you can add an option to force overwrite the unzip files. My worry is it will keep old files behind if that is not present in the update.  May be we should delete existing files `/mobsf/StaticAnalyzer/tools/jadx/` just after the zip download and before the unzip operation. So we don't want to fail unzip operation nor keep stale files behind from an older version.

**Comment by superpoussin22** [comment]
done for setup.sh and setup.bat, need to see the best way for docker :)

**Comment by Heufiih** [comment]
WHAT IS LIFE LIKE?!

Live! Don't just Exist! Don't drag through life. Live each day as a
Celebration! And Unlimited-Funds company is a very good platform to make
daily earnings and build a good income flow. Kindly contact the company to
start making daily earnings.
✔️✔️✔️✔️✔️✔️✔️✔️✔️✔️✔️✔️
http://unlimited-funds.co/?ref=Invest

**Comment by ajinabraham** [comment]
On windows
```
[INSTALL] Installing Jadx
C:\Users\xxx\Desktop\tmp\Mobile-Security-Framework-MobSF\venv\Scripts\python.exe: No module named gh-release-install
[ERROR] Impossible to download and install Jadx
```

**Comment by superpoussin22** [comment]
@ajinabraham can you check again on windows ?

**Comment by ajinabraham** [comment]
I can, But I think this will break mobsf install through [pypi](https://pypi.org/project/mobsf/) as setup script is not there in picture.

**Comment by superpoussin22** [comment]
@ajinabraham jadx installation is now a pyhton script but this script is not part of the CI , how to proceed ?

**Comment by ajinabraham** [comment]
@superpoussin22 Let's close this for now. I apologize for the wasted work you had already done here. We need something that can work across git based installs, python setup.py based/pypi installs, works cross platform and even in the CI. And I think that's too much work for the benefits we get from this. What do you think? If you think we can work on this further, I am open to test or help you.

**Comment by superpoussin22** [comment]
@ajinabraham  no worries I agree

**Pull request closed without merging**
