### PR TITLE
feat(page): recent scans add  page jumper

### PR DESCRIPTION
**Pull request by miaoyc666**
### Describe the Pull Request

When MobSF has a large amount of sample data in the system, the recent scans api speed has been very slow because it will retrieve full table data from the database.

To fix this, recent scans api add page jump, default display 10 items per page

Renderings
image

### Checklist for PR

- [x] Run MobSF unit tests and lint `tox -e lint,test`
- [x] Tested Working on Linux, Mac, Windows, and Docker
- [x] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [x] Make sure tests are passing on your PR [MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

### Additional Comments (if any)

```
DESCRIBE HERE
```

### CODE REVIEW

**Comment by ajinabraham** [comment]
Can you also include the changes in UI as well?

**Comment by miaoyc666** [comment]
> Can you also include the changes in UI as well?

Do you mean adding paging parameters in the fe as well?  Of course, it's just that it takes time. 😂

**Comment by miaoyc666** [comment]
> Can you also include the changes in UI as well?

@ajinabraham  ui done!

**Comment by ohyeah521** [comment]
@miaoyc666 Do you have any suggestions for optimizing the database? I found that when the amount of data exceeds 30,000, data query will become extremely slow, even if the page display is still very slow

**Comment by miaoyc666** [comment]
> @miaoyc666 Do you have any suggestions for optimizing the database? I found that when the amount of data exceeds 30,000, data query will become extremely slow, even if the page display is still very slow

@ohyeah521 

When you query a database, the first thing to control is the number of rows you query. You need to add offset and limit parameters to your SQL statement for pagination queries, limiting the number of rows returned.
Secondly, you need to select the fields that need to be displayed for select queries. Do not search for useless fields and cannot use select * because it will query all fields in a record, which will consume additional network bandwidth and CPU computing resources.
You can take a look at the code I commited, perform pagination queries in django, and only query the fields displayed on the page in the recent list of samples.

**Comment by ohyeah521** [comment]
@miaoyc666 thanks

**Comment by ajinabraham** [comment]
@miaoyc666 Thanks for taking your time and working on the UI bits. I will review this soon and get back to you.

**Comment by ajinabraham** [comment]
Initial testing looks good. I will see if I can improve up on the UI based on https://realpython.com/django-pagination/

**Pull request merged**
