### PR TITLE
Reduce Docker image size

### PR DESCRIPTION
**Pull request by superpoussin22**
### Describe the Pull Request

```
Reduce Docker image size 
WIP perhaps a move to buster ? => No interest 
```

### Checklist for PR

- [X] Run MobSF unit tests and lint `tox -e lint,test`.
- [X] Tested Working on Docker
- [X] Make sure build is passing on your PR. [Build Status](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/pull_requests)

### Additional Comments (if any)

```
none
```

### CODE REVIEW

**Comment by superpoussin22** [comment]
docker build works fine for me

**Comment by ajinabraham** [comment]
@superpoussin22 Good to merge?

**Comment by superpoussin22** [comment]
for me yes :)

**Comment by ajinabraham** [comment]
I am going to test this once at my end.

**Pull request merged**
