### PR TITLE
Fix Full RELRO/Partial RELRO/No RELRO check for Android

### PR DESCRIPTION
**Pull request by SektorROM**
### Describe the Pull Request

Returned string of relro() in mobsf/StaticAnalyzer/views/android/binary_analysis.py not properly checked in line 94 and 102, always leading to the "else" case in line 102 (no matter actual RELRO level of binary, always "No RELRO" is falsely shown).

This pull request fixes these checks accordingly.

### Checklist for PR

- [ OK] Run MobSF unit tests and lint `tox -e lint,test`
- [ Linux] Tested Working on Linux, Mac, Windows, and Docker
- [ - ] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [x] Make sure tests are passing on your PR [MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

### Additional Comments (if any)

iOS not impacted, as no RELRO there.

### CODE REVIEW

**Comment by ajinabraham** [comment]
Hi @SektorROM Thanks for the PR.
I am seeing the current logic working fine.

Screen Shot 2021-01-21 at 2 03 30 PM

Can you share the APK where you see RELRO not getting detected?

**Comment by SektorROM** [comment]
Hi,

can't share the exact APK due to reasons, but I'll create a new one and try to reproduce.
Strange it works on your side (also weird you have the 'high' tag visible, although 'Full RELRO' is good and should be 'info')

**Comment by ajinabraham** [comment]
Now that you mentioned, something looks not alright. will take a look again.

**Comment by SektorROM** [comment]
*Exactly. You ran into the case I mentioned (I got confused myself)

**Review by ajinabraham — APPROVED** [review]
Looks like this indeed is a bug

**Pull request merged**
