### PR TITLE
Fix API parameter 'rescan' default value

### LINKED ISSUE #1355: Scan not executed properly/incomplete when triggered via REST API
## ENVIRONMENT

```
OS and Python: from prebuild Docker Image (133f25036b647b27bd2e3301bf28fc56d5b15f0d62abaa7ee0ea5250089ff7da)
MobSF Version: v3.0.7 Beta
```

## EXPLANATION OF THE ISSUE

**TL;DR:** It seems that the REST API does not allow to perform a proper static analysis of an app (APK in my case) or at least it is incomplete. Complete scan is only performed via the browser.

_Wrong behavior:_
I can upload and scan the APK using the REST API but after that I cannot retrieve a JSON/PDF report (`"report": "Report not Found"`) via the API. However, accessing MobSF with my browser I see in "Recent Scans" that the scan is not completed. When I click on "Static Report" (in my browser) it seems that the scan is now executed properly/complete and all results are shown after analysis finished. Now I can get the results as JSON/PDF via the REST API as I expected

_Expected behavior:_
After upload and scan via REST API the scan should be completed and I can retrieve the report as JSON/PDF (also via REST API).

## STEPS TO REPRODUCE THE ISSUE

1. Upload APK using `api/v1/upload`. (This is successful, returning Status 200. And APK shows up in the list of recent scans as not completed.)
2.  Then I request to scan the APK via REST-API `api/v1/scan`. (The app is still shown as "scan not completed" in the list of recent scans in browser, but now with its icon. The scan is also listed in `api/v1/scan`.)
3. I try to request a report as JSON or PDF via `api/v1/report_json` or `api/v1/download_pdf`. But I get `{"report": "Report not Found"}` back from the API.
4. After that I go with my browser to the site with the Static Analysis report. This seems to cause another scan. After some time I get the results and in the list of recent scans the "scan not completed" badge is gone.
5. When trying again to get JSON or PDF report (as in step 3) everything works fine. I get the report as JSON and PDF.

## LOG FILE

```
[INFO] 14/Apr/2020 13:20:04 - MIME Type: application/octet-stream FILE: 1491928811_com.starfinanz.smob.android.sfinanzstatus_41206_04-11-2017.apk
[INFO] 14/Apr/2020 13:20:04 - Performing Static Analysis of Android APK
[INFO] 14/Apr/2020 13:21:49 - Starting Analysis on : 1491928811_com.starfinanz.smob.android.sfinanzstatus_41206_04-11-2017.apk
[INFO] 14/Apr/2020 13:21:49 - Generating Hashes
[INFO] 14/Apr/2020 13:21:49 - Unzipping
[INFO] 14/Apr/2020 13:21:50 - Getting Hardcoded Certificates/Keystores
[INFO] 14/Apr/2020 13:21:50 - APK Extracted
[INFO] 14/Apr/2020 13:21:50 - Converting AXML to XML
[INFO] 14/Apr/2020 13:21:56 - Reading Android Manifest
[INFO] 14/Apr/2020 13:21:56 - Parsing AndroidManifest.xml
[INFO] 14/Apr/2020 13:21:58 - Fetching icon path
[INFO] 14/Apr/2020 13:22:01 - Extracting Manifest Data
[INFO] 14/Apr/2020 13:22:01 - Fetching Details from Play Store: com.starfinanz.smob.android.sfinanzstatus
[INFO] 14/Apr/2020 13:22:01 - Manifest Analysis Started
[INFO] 14/Apr/2020 13:22:01 - Static Android Binary Analysis Started
[INFO] 14/Apr/2020 13:22:01 - Static Android Resource Analysis Started
[INFO] 14/Apr/2020 13:22:01 - Reading Code Signing Certificate
[INFO] 14/Apr/2020 13:22:01 - Running APKiD 2.1.0
[INFO] 14/Apr/2020 13:22:05 - Updating Trackers Database....
[INFO] 14/Apr/2020 13:22:05 - Detecting Trackers
[INFO] 14/Apr/2020 13:22:07 - APK -> JAVA
[INFO] 14/Apr/2020 13:22:07 - Decompiling to Java with jadx
[INFO] 14/Apr/2020 13:22:27 - DEX -> SMALI
[INFO] 14/Apr/2020 13:22:27 - Converting classes.dex to Smali Code
[INFO] 14/Apr/2020 13:22:27 - Converting classes2.dex to Smali Code
[INFO] 14/Apr/2020 13:22:27 - Static Android Code Analysis Started
[INFO] 14/Apr/2020 13:22:27 - Code Analysis Started on - java_source
[INFO] 14/Apr/2020 13:22:40 - Finished Code Analysis, Email and URL Extraction
[INFO] 14/Apr/2020 13:22:40 - Extracting Strings from APK
[INFO] 14/Apr/2020 13:22:43 - Detecting Firebase URL(s)
[INFO] 14/Apr/2020 13:22:43 - Performing Malware Check on extracted Domains
[INFO] 14/Apr/2020 13:22:44 - Updating Malware Database....
[INFO] 14/Apr/2020 13:22:46 - Connecting to Database
[WARNING] 14/Apr/2020 13:28:06 - Not Found: /api/v1/download_pdf
[INFO] 14/Apr/2020 13:31:36 - Starting Analysis on : 1491928811_com.starfinanz.smob.android.sfinanzstatus_41206_04-11-2017.apk
[INFO] 14/Apr/2020 13:31:36 - Generating Hashes
[INFO] 14/Apr/2020 13:31:36 - Unzipping
[INFO] 14/Apr/2020 13:31:37 - Getting Hardcoded Certificates/Keystores
[INFO] 14/Apr/2020 13:31:37 - APK Extracted
[INFO] 14/Apr/2020 13:31:37 - Reading Android Manifest
[INFO] 14/Apr/2020 13:31:37 - Parsing AndroidManifest.xml
[INFO] 14/Apr/2020 13:31:39 - Fetching icon path
[INFO] 14/Apr/2020 13:31:41 - Extracting Manifest Data
[INFO] 14/Apr/2020 13:31:41 - Fetching Details from Play Store: com.starfinanz.smob.android.sfinanzstatus
[INFO] 14/Apr/2020 13:31:41 - Manifest Analysis Started
[INFO] 14/Apr/2020 13:31:41 - Static Android Binary Analysis Started
[INFO] 14/Apr/2020 13:31:41 - Static Android Resource Analysis Started
[INFO] 14/Apr/2020 13:31:41 - Reading Code Signing Certificate
[INFO] 14/Apr/2020 13:31:41 - Running APKiD 2.1.0
[INFO] 14/Apr/2020 13:31:44 - Trackers Database is up-to-date
[INFO] 14/Apr/2020 13:31:44 - Detecting Trackers
[INFO] 14/Apr/2020 13:31:46 - APK -> JAVA
[INFO] 14/Apr/2020 13:31:46 - Decompiling to Java with jadx
[INFO] 14/Apr/2020 13:32:05 - DEX -> SMALI
[INFO] 14/Apr/2020 13:32:05 - Converting classes.dex to Smali Code
[INFO] 14/Apr/2020 13:32:05 - Converting classes2.dex to Smali Code
[INFO] 14/Apr/2020 13:32:05 - Static Android Code Analysis Started
[INFO] 14/Apr/2020 13:32:05 - Code Analysis Started on - java_source
[INFO] 14/Apr/2020 13:32:19 - Finished Code Analysis, Email and URL Extraction
[INFO] 14/Apr/2020 13:32:19 - Extracting Strings from APK
[INFO] 14/Apr/2020 13:32:21 - Detecting Firebase URL(s)
[INFO] 14/Apr/2020 13:32:21 - Performing Malware Check on extracted Domains
[INFO] 14/Apr/2020 13:32:22 - Malware Database is up-to-date
[INFO] 14/Apr/2020 13:32:23 - Connecting to Database
[INFO] 14/Apr/2020 13:32:23 - Saving to Database
[INFO] 14/Apr/2020 13:33:27 - Fetching data from DB for PDF Report Generation (Android)
[INFO] 14/Apr/2020 13:33:27 - Analysis is already Done. Fetching data from the DB...
[INFO] 14/Apr/2020 13:33:27 - Generating PDF report for android apk
```

### PR DESCRIPTION
**Pull request by flubshi**
### Describe the Pull Request

When using the MobSF API, I was affected by the issue #1355. For interacting with the API, I was using https://github.com/klmmr/mobsfpy

**Issue:**
The scan was incomplete, when using the [scan function from library](https://github.com/klmmr/mobsfpy/blob/908fb22c1ff9edc8e5d85c5c509ecff854550489/mobsfpy/mobsf.py#L39)

**Reason:**
mobsfpy sets `re_scan = False` instead of `rescan = 0`. Of course, mobsfpy should pass the correct value (0 or 1). But I would expect that MobSF API uses the default if it is not the case. As a result, the final scan result is not saved.

To be more precise, the variable `rescan` in current implementation can have different values that `0` or `1`, which means `save_or_update` is not executed,[see here](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/18f4a483d361e704a795bea416f5eb968860b068/mobsf/StaticAnalyzer/views/android/static_analyzer.py#L84):

```python
rescan = str(request.POST.get('re_scan', 0)) // rescan can be everything

[...]

                        if rescan == '1':
                            logger.info('Updating Database...')
                            save_or_update(
                                [...]
                            )
                            update_scan_timestamp(app_dic['md5'])
                        elif rescan == '0':
                            logger.info('Saving to Database')
                            save_or_update(
                                [...]
                            )
```

If it is not explicitly "0" or "1", e.g. "2", False or "<random string>", `save_or_update` is not executed.

This PR fixes this behavior. I use `request.POST.get('re_scan', '0') != '0'` to be backwards compatible and assign local variable `rescan` a boolean. If request paremter `rescan = 0` is passed or `rescan` is not set, the value defaults to `False`.

The simplified code above becomes (this PR):

```python
                        if rescan:
                            logger.info('Updating Database...')
                            save_or_update(
                                [...]
                            )
                            update_scan_timestamp(app_dic['md5'])
                        else:
                            logger.info('Saving to Database')
                            save_or_update(
                                [...]
                            )
```

This ensures `save_or_update` to be executed.

Fixes #1355

### Checklist for PR

- [ ] Run MobSF unit tests and lint `tox -e lint,test`
- [ ] Tested Working on Linux, Mac, Windows, and Docker
- [ ] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [x] Make sure tests are passing on your PR [MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

### Additional Comments (if any)

```
Tested with Android on Linux.
```

### CODE REVIEW

**Comment by ajinabraham** [comment]
As discussed here: https://github.com/klmmr/mobsfpy/pull/4#issuecomment-775711145
This is expected behavior and `re_scan` is an optional variable that has significance only when set to `1`.

**Comment by flubshi** [comment]
According to the discussion in the other PR, we should make MobSF failsafe. Either by this PR or, with minimum changes, by replacing `elif rescan == '0':` with `else:`. In this case, invalid parameters would prevent from saving the results.

Whats do you think?

**Comment by ajinabraham** [comment]
We do not want MobSF to accept anything for `re_scan` other than a 0 or 1. But for what it is worth, we can accept a change from `elif` to an `else`.

**Comment by ajinabraham** [comment]
Added changes to make MobSF rescan fail-safe.

**Review by ajinabraham — APPROVED** [review]

**Comment by flubshi** [comment]
Thanks for merging the PR and making the API more fail-safe.

TBH, I do not understand why you stick to using a string for representing a boolean value, which is bad practice in my opinion. But it is up to you...

**Comment by ajinabraham** [comment]
The `request` object always returns a `string` or a `None`.  So at someplace, you will have to convert it into a boolean. And since you cannot supply boolean to a request object. It really didn't make any sense to expect or have boolean values.

**Comment by flubshi** [comment]
Just to say it: I respect the time and effort you invest in this project. I think you are doing a great job - thank you! It is no criticism in you as person - and maybe you didn't wrote the affected code.

But what I am talking about: The rescan yes/no decision based on the request string, is performed multiple times, for each platform (Android/iOS/Windows) - why not evaluating the rescan yes/no decision before calling the platform specific checks. 

I mean - you can see the duplicated code in the static_analyzer.py for each platform.

**Comment by ajinabraham** [comment]
> But what I am talking about: The rescan yes/no decision based on the request string, is performed multiple times, for each platform (Android/iOS/Windows) - why not evaluating the rescan yes/no decision before calling the platform specific checks.

Make sense. I will update the logic.

**Pull request merged**
