### PR TITLE
Update icon_analysis.py

### PR DESCRIPTION
**Pull request by superpoussin22**
1st correction . need now to understand why the Hidden icon image is not displayed

### CODE REVIEW

**Comment by ajinabraham** [comment]
@matandobr Do add a review comment.

**Comment by superpoussin22** [comment]
@matandobr  xml file is an adaptive icon, androguard team is working on it, so, my test sounds Ok until they found a solution 

https://github.com/androguard/androguard/pull/454

**Comment by matandobr** [comment]
So we leave it like that for now? We don't have the hidden icon anomaly anymore and that sucks..

**Comment by superpoussin22** [comment]
@matandobr  perhaps we could open a ticket for hidden icon anomaly and if you have some apk hash I can use to diagnose the issue, I will work on it  but merge this PR to enhance icon display ?

**Comment by ajinabraham** [comment]
LGTM 👍

**Pull request merged**
