### PR TITLE
Code QA, Bug Fix #861

### LINKED ISSUE #861: Exception while resolving variable 'exp' in template 'general/error.html
Static Analysis works absolutely fine but when i try to do dynamic analysis I get the following error. Might be [this](https://stackoverflow.com/questions/40066019/django-1-10-exception-while-resolving-variable-is-popup-in-template-admin-log) is the reason. Because I am not very much aware of the app structure, it's difficult for me to troubleshoot.

```
[INFO] 08/Feb/2019 16:17:54 - VM Starting
[INFO] 08/Feb/2019 16:17:55 - "POST /DynamicAnalyzer/ HTTP/1.1" 200 32400
[INFO] 08/Feb/2019 16:17:55 - "GET /static/css/devices.min.css HTTP/1.1" 200 44241
[INFO] 08/Feb/2019 16:17:55 - "GET /download/screen/screen.png HTTP/1.1" 302 0
[DEBUG] 08/Feb/2019 16:17:55 - Exception while resolving variable 'exp' in template 'general/error.html'.
Traceback (most recent call last):
  File "/home/userhome/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/template/base.py", line 829, in _resolve_lookup
    current = current[bit]
  File "/home/userhome/Mobile-Security-Framework-MobSF/venv/lib/python3.6/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'exp'

During handling of the above exception, another exception occurred:
```

### PR DESCRIPTION
**Pull request by superpoussin22**
remove [INFO] in message

### Describe the Pull Request

```
Remove dupliave[INFO] in messages 
```

### Checklist for PR

- [X] Run MobSF unit tests (http://your-mobsf-@ip:8000/tests/ or python3 manage.py test).
- [X] Tested Working on Linux, Mac, Windows, and Docker
- [X] Make sure build is passing on your PR. [Build Status](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/pull_requests)
- [X] Coding style (indentation, etc)

### CODE REVIEW

**Comment by ajinabraham** [comment]
Good idea, Can you remove it in other files too?
https://github.com/MobSF/Mobile-Security-Framework-MobSF/search?q=%5BINFO%5D&unscoped_q=%5BINFO%5D

Search for `[INFO]` , `[ERROR]` , `[WARNING]`

**Comment by superpoussin22** [comment]
@ajinabraham sounds good

**Comment by superpoussin22** [comment]
> Good idea, Can you remove it in other files too?
> https://github.com/MobSF/Mobile-Security-Framework-MobSF/search?q=%5BINFO%5D&unscoped_q=%5BINFO%5D
> 
> Search for `[INFO]` , `[ERROR]` , `[WARNING]`

done

**Comment by ajinabraham** [comment]
@superpoussin22  There is more: https://github.com/MobSF/Mobile-Security-Framework-MobSF/search?q=%5BERROR%5D&unscoped_q=%5BERROR%5D
Search for [ERROR] and [WARNING]

**Comment by superpoussin22** [comment]
> @superpoussin22 There is more: https://github.com/MobSF/Mobile-Security-Framework-MobSF/search?q=%5BERROR%5D&unscoped_q=%5BERROR%5D
> Search for [ERROR] and [WARNING]

@ajinabraham  no problem will check,  I focused on info :)

**Comment by ajinabraham** [comment]
* Refactored Logging
* Improved UI Error Display
* Fixed Bug in Dynamic Analysis https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/861

**Pull request merged**
