### PR TITLE
it's better not to use `apt` in scripts

### PR DESCRIPTION
**Pull request by aminvakil**
### Describe the Pull Request
Taken from man apt:
```
apt provides a high-level commandline interface for the package management system. It is intended as an end user interface and enables some options better suited for interactive usage by default compared to more specialized APT tools like apt-get(8) and apt-cache(8).
```

### Checklist for PR

- [ ] Run MobSF unit tests and lint `tox -e lint,test`
- [x] Tested Working on Linux, Mac, Windows, and Docker
- [ ] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [ ] Make sure tests are passing on your PR [MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

### CODE REVIEW

**Comment by ajinabraham** [comment]
`apt should not be used in scripts` is there a documentation that states `apt` should not be used in cli / dockerfile?

**Comment by aminvakil** [comment]
> `apt should not be used in scripts` is there a documentation that states `apt` should not be used in cli / dockerfile?

As mentioned in PR description, here is also a link:
https://manpages.debian.org/bullseye/apt/apt.8.en.html

apt provides a high-level commandline interface for the package management system. It is intended as an end user interface and enables some options better suited for interactive usage by default compared to more specialized APT tools like apt-get(8)and apt-cache(8).

**Comment by ajinabraham** [comment]
Yes, but there is nothing that says you should not use `apt` in scripts.

**Comment by aminvakil** [comment]
> Yes, but there is nothing that says you should not use `apt` in scripts.

I changed title of my PR.

**Comment by ajinabraham** [comment]
Unless there are issues with using `apt`, I am reluctant towards this change as this does not bring any improvement on what's already there.

**Comment by aminvakil** [comment]
`apt` does not need to be backward-compatible like `apt-get` should be, I'm not saying that maybe someday `apt install package -y` will not work, but it feels better to use something that is intended to backward compatible.

**Comment by ajinabraham** [comment]
I am closing this PR as the change does not particularly fix anything that's broken now or documented to be broken in the near future. We can always revisit once it's officially recommend to use `apt-get` instead of `apt` for CLI.

**Pull request closed without merging**
