### PR TITLE
Revert scoring algorithm

### LINKED ISSUE #1940: App Security Score inconsistencies
## ENVIRONMENT

```
OS and Version: all
Python Version: all
MobSF Version: 3.5.0
```

## EXPLANATION OF THE ISSUE

I'm noticing some inconsistencies in security scores since the release of 3.5.0.

I ran a static analysis on 2 applications and got these results :
image
image

With this new security_score formula 
image
the security scores obtained are 36/100 and 39/100. So basically the first one which has way more findings receives a worse score ?

I understand the intention to ponder the score based on the ratio of the finding's criticity but that case seems to be a bit extreme.

### PR DESCRIPTION
**Pull request by devtty1er**
Fixes #1940 

### Checklist for PR

- [x] Run MobSF unit tests and lint `tox -e lint,test`
- [x] Tested Working on Linux, Mac, Windows, and Docker
- [x] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [x] Make sure tests are passing on your PR [MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

### CODE REVIEW

**Comment by ajinabraham** [comment]
We cannot revert the scoring logic. There are some outstanding issues that needs to be addressed.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1940

**Comment by ajinabraham** [comment]
Closing this for now.

**Comment by devtty1er** [comment]
"We *cannot* revert the scoring logic" is an oddly strong statement for something that is totally broken.

As @Prehistoic, @johnxguo and I have mentioned, more warnings can lead to higher (better) score.

**To all MobSF users, I strongly recommend treating the score as useless, since it is.**

**Comment by ajinabraham** [comment]
As you know, the current scoring logic is not our first implementation. We had previous implementations which had issues and feedback from the community, thats why we had to update them. The current implementation is also not perfect, hence we have an open ticket to track it
https://github.com/MobSF/Mobile-Security-Framework-MobSF/issues/1940

Reverting to the old algorithm doesn’t give a holistic solution to the problem. If you have an alternative scoring proposal PR we are happy to review it and merge it.

**Pull request closed without merging**
