### PR TITLE
Added A Deep Link Viewer 

### PR DESCRIPTION
**Pull request by Shapa7276**
I have written a small script to parse the deep links (https://github.com/Shapa7276/Android-Deeplink-Parser) 

and I found it is not properly implemented in Mobsf,  I have added the code  , So MobSF can show us all deeplinks 

 Button 

1)added 'deep_view.py' file to parse deeplink

2)"android_binary_analysis.html" added button to redirect

3)'urls.py' was modified to view 'deep_view' URL

### Describe the Pull Request

```
DESCRIBE THE DETAILS OF PULL REQUEST HERE
```

### Checklist for PR

- [ *] Run MobSF unit tests and lint `tox -e lint,test`
```
- LL TESTS COMPLETED!                                                                                                                                          
[INFO] 03/Sep/2021 10:01:40 - Test Status: some tests failed
[WARNING] 03/Sep/2021 10:01:40 - Forbidden: /tests/
F
======================================================================
FAIL: test_rest_api (mobsf.StaticAnalyzer.tests.StaticAnalyzerAndAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kali/tools/githubtemp/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/tests.py", line 425, in test_rest_api
    self.assertEqual(resp.status_code, 200)
AssertionError: 403 != 200

======================================================================
FAIL: test_static_analyzer (mobsf.StaticAnalyzer.tests.StaticAnalyzerAndAPI)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/kali/tools/githubtemp/Mobile-Security-Framework-MobSF/mobsf/StaticAnalyzer/tests.py", line 421, in test_static_analyzer
    self.assertEqual(resp.status_code, 200)
AssertionError: 403 != 200

----------------------------------------------------------------------
Ran 2 tests in 205.392s

FAILED (failures=2)
Destroying test database for alias 'default'...
ERROR: InvocationError for command /usr/bin/bash -c '. venv/bin/activate && python manage.py test mobsf' (exited with code 1)
__________________________________________________________________________ summary ___________________________________________________________________________
ERROR:   lint: commands failed
ERROR:   test: commands failed                                                                                                                                
```
- [ *] Tested Working on Linux,
- [ *] Add unit test for any new Web API (Refer: `StaticAnalyzer\views\android\deep_view.py`)
- [ ] Make sure tests are passing on your PR [MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

### Additional Comments (if any)

```
DESCRIBE HERE
```

### CODE REVIEW

**Comment by superpoussin22** [comment]
@ajinabraham : sounds good for me

**Comment by ajinabraham** [comment]
Thanks for the PR. I am on vacation. Will take a look once I am back.

**Review by Shapa7276 — COMMENTED** [review]
looks good, have you updated remaining files as well ?

**Comment by superpoussin22** [comment]
@Shapa7276  no the deep_view.py need to be formated correctly as explained by the linter

**Comment by Shapa7276** [comment]
Hey all these lint  errors are for long lines on and I guess thats are acceptable

**Comment by ajinabraham** [comment]
We split long lines into multiple lines throughout most of the project.

**Comment by Shapa7276** [comment]
@ajinabraham  are pushing above code ?

**Comment by ajinabraham** [comment]
Can you please remove the additional endpoint and add it to the existing static analysis view?

**Comment by ajinabraham** [comment]
After the requested changes are made.

**Comment by ajinabraham** [comment]
Closing due to no activity

**Pull request closed without merging**
