### PR TITLE
Dockerfile maintenance

### PR DESCRIPTION
**Pull request by OscarAkaElvis**
Changes on Dockerfile to keep it updated.

### CODE REVIEW

**Comment by ajinabraham** [comment]
Reviewing Code

**Comment by ajinabraham** [comment]
Please refer: https://stackoverflow.com/questions/28335977/running-aapt-on-64-bit-ubuntu-12-04-error-while-loading-shared-libraries-libc
and see if it's helpful

**Comment by OscarAkaElvis** [comment]
This error is not related to my pull request. Anyway I found the solution. I'll push it very soon.

**Comment by ajinabraham** [comment]
LGTM 👍

**Pull request merged**
