### PR TITLE
new apkid rules

### PR DESCRIPTION
**Pull request by superpoussin22**
Better detection of Dexprotector 

It should be merged also in apkid official website :)

### CODE REVIEW

**Comment by ajinabraham** [comment]
@superpoussin22 Can I find the original rules?

**Comment by superpoussin22** [comment]
@ajinabraham https://github.com/rednaga/APKiD/pull/89/files

**Comment by ajinabraham** [comment]
I will wait for APKiD to merge this first.

**Comment by superpoussin22** [comment]
will reopen a new one

**Pull request closed without merging**
