### PR TITLE
GitHub Action to lint Python code

### PR DESCRIPTION
**Pull request by cclauss**
### GitHub Action to lint Python code
Output: https://github.com/cclauss/Mobile-Security-Framework-MobSF/actions

```
DESCRIBE THE DETAILS OF PULL REQUEST HERE
```

### Checklist for PR

- [ ] Run MobSF unit tests and lint `tox -e lint,test`
- [ ] Tested Working on Linux, Mac, Windows, and Docker
- [ ] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [ ] Make sure tests are passing on your PR [MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

### Additional Comments (if any)

```
DESCRIBE HERE
```

### CODE REVIEW

**Comment by ajinabraham** [comment]
Hi @cclauss, Thanks for the PR!

Can this be moved to `https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/tox.ini` ?
We run tests and lint both locally and in github using tox.

**Comment by cclauss** [comment]
Did you look at https://github.com/pre-commit ?  This is a way to automate testing such that git commit are gated by passing tests.  This also makes it easy to have a GitHub Action of the form:
```yaml
# https://pre-commit.com
# This GitHub Action assumes that the repo contains a valid .pre-commit-config.yaml file.
name: pre-commit
on:
  pull_request:
  push:
    branches: [master]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install pre-commit
      - run: pre-commit --version
      - run: pre-commit install
      - run: pre-commit run --all-files
```

I will try to retool towards `tox` in the meantime.

**Comment by ajinabraham** [comment]
pre-commit make sense for lint checks, but we cannot run tests on pre-commit as they are pretty time consuming.

**Comment by ajinabraham** [comment]
Stale, Closing.

**Pull request closed without merging**
