### PR TITLE
Get the executable file name from the info.plist

### PR DESCRIPTION
**Pull request by muer2000**
### What was a problem?

```
DESCRIBE HERE
```

### How this PR fixes the problem?

```
DESCRIBE HERE
```

### Check lists (check `x` in `[ ]` of list items)

- [ ] Run MobSF unit tests
- [ ] Tested Working on Linux, Mac, and Windows
- [ ] Coding style (indentation, etc)

### Additional Comments (if any)

```
DESCRIBE HERE
```

### CODE REVIEW

**Comment by magaofei** [comment]
Thank you. 
Please provide more information, What problem has been solved?

**Comment by ajinabraham** [comment]
@magaofei Is this relevant, now that we have a PR that reads `Info.plist` properly?

**Comment by magaofei** [comment]
@ajinabraham I don't quite understand the problem with this merge request.

**Comment by ajinabraham** [comment]
@magaofei From the code, it looks to me. If we failed to get the binary name from extracted IPA dir, it is fetched from Info.plist.

**Pull request merged**
