### PR TITLE
Saving the dynamic results

### PR DESCRIPTION
**Pull request by matandobr**
Once done, the dynamic results should be accessible again

### CODE REVIEW

**Comment by ajinabraham** [comment]
Is this under dev?

**Comment by matandobr** [comment]
I think it's working fine, except there is no way to delete the results from the ui now, I can add this functionality inside the static "reanalyze" function, or to separate it. What do you think?

**Comment by ajinabraham** [comment]
@matandobr Cool. I will do a review of the code. 
I think how it works now is by overwriting the previous scan results which is fine for dynamic analyser. The delete function needs to be implemented to the page that shows the scan result.

**Comment by matandobr** [comment]
Okay not a problem, I'll send an update

**Comment by ajinabraham** [comment]
Also where we list the Recent Scan, IIRC.

**Comment by ajinabraham** [comment]
Next time you make a PR. It will be easy if you create a branch from the main repo.

**Comment by ajinabraham** [comment]
@matandobr I think is good and easy hack to show the dynamic analysis report.
Don't add to Recent Scan. But a delete function that will extend the delete button in `http://127.0.0.1:8000/recent_scans/` would be great. essentially it should delete the db scan results for static analysis and the files created during dynamic analysis.

**Pull request merged**
