### PR TITLE
[WIP-Dont Merge]Replace Jtoolv1 with Jtoolv2

### PR DESCRIPTION
**Pull request by superpoussin22**
### Describe the Pull Request

```
replace jtoolv1 with jtoolv2 more speedy and powerful 
jtoolv1 is deprecated
```

### Checklist for PR

- [X] Run MobSF unit tests and lint `tox -e lint,test`.
- [X] Tested Working on Linux and Docker
- [X] Make sure build is passing on your PR. [Build Status](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/pull_requests)

### CODE REVIEW

**Comment by ajinabraham** [comment]
@superpoussin22 How are things going here?

**Comment by superpoussin22** [comment]
jtool2 is more speedy and support more format but we loose the 32bit ipa support :( 
Don't know if it is too soon to migrate to jtool2 event if jtool is deprecated and can crash with some new ipa .  We coudl perhaps consider that because 32b ipa are no more accepted by Appel (if I'm not wrong) we can cut the 32bit support ?

**Comment by ajinabraham** [comment]
I don't think we should cut support for 32 bit as old IPAs are still around. We can only consider that if the new IPAs are generally crashing with old jtool. I find no issues so far.

**Comment by superpoussin22** [comment]
Agree  so closing 
will check with jtool dev if he will add 32 support or not

**Pull request closed without merging**
