### PR TITLE
OWASP Mobile Top 10 2016 support and better App Security scoring

### PR DESCRIPTION
**Pull request by ajinabraham**
### Describe the Pull Request

```
OWASP Mobile Top 10 2016 Support and Better App Security Scoring
```

### Checklist for PR

- [x] Run MobSF unit tests and lint `tox -e lint,test`.
- [x] Tested Working on Linux, Mac, Windows, and Docker
- [x] Make sure build is passing on your PR. [Build Status](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/pull_requests)

### Additional Comments (if any)

```
DESCRIBE HERE
```

### CODE REVIEW

**Comment by superpoussin22** [comment]
[INFO] 04/Oct/2019 21:08:24 - Code Analysis Started on - java_source
[ERROR] 04/Oct/2019 21:08:32 - Error in Code Rule Processing
Traceback (most recent call last):
  File "/Users/vince/Documents/Dev/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/shared_func.py", line 386, in code_rule_matcher
    'desc'], file_path, rule)
  File "/Users/vince/Documents/Dev/Mobile-Security-Framework-MobSF/StaticAnalyzer/views/shared_func.py", line 325, in add_findings
    'owasp': rule['owasp']}
KeyError: 'owasp'

**Comment by ajinabraham** [comment]
@superpoussin22 Do you have a file with which I can reproduce this?

**Comment by superpoussin22** [comment]
> @superpoussin22 Do you have a file with which I can reproduce this?

https://play.google.com/store/apps/details?id=im.team&hl=fr

**Comment by superpoussin22** [comment]
I think it's happen when there's no owasp value to map with

**Comment by ajinabraham** [comment]
@superpoussin22 That's the reason. Can you please pull the branch and try again?

**Comment by superpoussin22** [comment]
perfect :)

**Pull request merged**
