### PR TITLE
correction1

### PR DESCRIPTION
**Pull request by PaulAnton**
taking the part of the IP before the forward slash- this way it will avoid the part that might contain 127.0.0.1. what would be the format of the urllist? assuming it will have just the part before the forward slash- this code should work fine

### CODE REVIEW

**Comment by PaulAnton** [comment]
#415

**Comment by ajinabraham** [comment]
Reviewing and Testing Code.

**Comment by ajinabraham** [comment]
I did an alternate fix.

**Comment by ajinabraham** [comment]
Fixed in https://github.com/MobSF/Mobile-Security-Framework-MobSF/commit/9aed2b8b3328d7ae001fce90a87242cc71eae0d1

**Pull request closed without merging**
