### PR TITLE
Update README.md for Docker Syntax

### PR DESCRIPTION
**Pull request by superpoussin22**
update docker  syntax

### Describe the Pull Request

```
Make Mobsf run in background and give a name to the container 
Docker option documentation apge will be updated too 
```

### Checklist for PR

- [X] Run MobSF unit tests and lint `tox -e lint,test`.
- [X] Tested Working on Linux, Mac, Windows, and Docker
- [X] Make sure build is passing on your PR. [Build Status](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/pull_requests)

### CODE REVIEW

**Comment by ajinabraham** [comment]
@superpoussin22 That's up-to user to run in daemon mode. It will be difficult to track status, logs or errors in daemon mode.

**Comment by superpoussin22** [comment]
we could add the command to see logs ? 
docker logs -f --tail 100 mobsf 

or let it as it is :) as you want

**Comment by ajinabraham** [comment]
@superpoussin22 The people who barely know to use docker will have difficulties in seeing logs and making it difficult for us  to troubleshoot. Power docker users will already know these options and we don't have to document that.

**Comment by superpoussin22** [comment]
Not needed

**Pull request closed without merging**
