### PR TITLE
Add the checking of the parent element of the permission-related elements to manifest analysis

### PR DESCRIPTION
**Pull request by Han0nly**
### Describe the Pull Request

```
Hi, The parent element of <permission>,<uses-permission>, <uses-permission-sdk-23> elements can only be <manifest>, or these statements would not take effect. According to an empirical study of a paper, this kind of bug is very common. So in this pull request I add the checking of the parent node of these elements to the manifest analysis part.
```

### Checklist for PR

- [*] Run MobSF unit tests and lint `tox -e lint,test`
- [*] Tested Working on Linux, Mac, Windows, and Docker
- [*] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [*] Make sure tests are passing on your PR [MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

### Additional Comments (if any)

```
In this pull request, I only add the checking of the permission elements, but I'll continuously add all the other manifest structure checking functionalities later.
```

### CODE REVIEW

**Comment by ajinabraham** [comment]
Hi @Han0nly  Could you please elaborate on the security impact of this findings? Is there a reference that explains the security impact of the bug?

**Comment by Han0nly** [comment]
Hi @ajinabraham. You can refer to the IV-D section of [this paper](https://ieeexplore.ieee.org/document/7962352) for more details.

I can briefly describe the security implications of this issue as follows:

Permissions are declared using  \<uses-permission\> or \<uses-permission-sdk-23\> elements  whose immediate parent element must be \<manifest\>. Incorrect elements, as well as incorrect parent elements in declaring permission names implicate that the app accesses resources without declaring the required permissions. If such an app tries to access the resource during execution then a  security exception is thrown. For example, in this paper, the authors found 8 custom permissions defined in 8 apps whose immediate parent element is  \<application\> instead of \<manifest\>. For example, in this paper, the authors found 44 apps declaring permissions in incorrect parent elements such as \<application>,\<activity\>, and \<intent-filter\>. 

Permissions are defined using \<permission\>  elements whose immediate parent element must be  \<manifest\>. Defining custom permissions in inappropriate places implicates that resources protected with such incorrectly defined custom permissions are indeed unprotected. For example, in this paper, the authors found 8 custom permissions  defined in 8 apps whose immediate parent element is  \<application\> instead of \<manifest\>. 


[2017-2017 IEEE-ACM 14th International Conference on Mining Software Repositories (MSR)-Developer Mistakes in Writing Android Manifests- An Empirical Study of Configuration Errors-Jha.pdf](https://github.com/MobSF/Mobile-Security-Framework-MobSF/files/8084650/2017-2017.IEEE-ACM.14th.International.Conference.on.Mining.Software.Repositories.MSR.-Developer.Mistakes.in.Writing.Android.Manifests-.An.Empirical.Study.of.Configuration.Errors-Jha.pdf).

**Comment by ajinabraham** [comment]
I will take a look at this and get back. Thanks for your patience.

**Comment by ajinabraham** [comment]
I need a bit more time in reviewing this. Thanks for your patience.

**Review by ajinabraham — APPROVED** [review]

**Comment by ajinabraham** [comment]
Thanks for your patience @Han0nly . This will be merged soon.

**Review by ajinabraham — CHANGES_REQUESTED** [review]
@Han0nly We are seeing test failures

**Comment by Han0nly** [comment]
Hi @ajinabraham , sorry for the inconvinence. I fixed the non-serializable error and tested on Ubuntu 20.04 and MacOS.

**Review by ajinabraham — APPROVED** [review]
LGTM

**Pull request merged**
