### PR TITLE
iOS IPA CVSS, CWE, Binary Information, IPA Binary Detection and Classdump for swift binaries

### PR DESCRIPTION
**Pull request by ajinabraham**
### Describe the Pull Request

```
This PR adds 
* CVSS, CWE and Binary Information for iOS IPA binaries.
* iOS IPA binary type detection and classdump for swift binaries
```

### Checklist for PR

- [x] Run MobSF unit tests (http://your-mobsf-@ip:8000/tests/ or python3 manage.py test).
- [x] Tested Working on Linux, Mac, Windows, and Docker
- [x] Make sure build is passing on your PR. [Build Status](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/pull_requests)
- [x] Coding style (indentation, etc)

### Additional Comments (if any)

```
DESCRIBE HERE
```

### CODE REVIEW

**Comment by superpoussin22** [comment]
{'endian': '<', 'bit': '64-bit', 'arch': 'ARM64', 'subarch': 'CPU_SUBTYPE_ARM64_ALL'}

**Comment by ajinabraham** [comment]
@superpoussin22 This is from macholib.
See https://bitbucket.org/ronaldoussoren/macholib/src/e287095a0b4a02dccb7537c9d1de904dc0f45cc2/macholib/MachO.py?at=default&fileviewer=file-view-default#MachO.py-133

**Comment by iHTCboy** [comment]
@ajinabraham 

[StaticAnalyzer/views/ios/binary_analysis.py](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/79dba9173d52b978ce872c3758d60071770efe06/StaticAnalyzer/views/ios/binary_analysis.py) ：

```
if b'Source: (null)' in classdump and platform.system() == 'Darwin':
            logger.info('Running fail safe class-dump-swift')
```

I would like to ask, what is the basis of this method's `b"Source: (null)"`? 

thank!

**Comment by ajinabraham** [comment]
It is the default response when analysis fails.

**Pull request merged**
