### PR TITLE
website display error in debug mode

### PR DESCRIPTION
**Pull request by XmTX1994**
```
When running in debug mode, page cannot display properly.
```

### CODE REVIEW

**Comment by ajinabraham** [comment]
I am sorry, could you please briefly explain about this debug mode issue that needs this fix?

MobSF by default runs on debug mode and haven't noticed any issues.
https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/MobSF/settings.py#L152

**Comment by XmTX1994** [comment]
In settings.py file, when I set DEBUG = True, page like this:
image

So, I think following code should be added
if DEBUG:
    STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'), )
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')

**Comment by ajinabraham** [comment]
When I am running as per the docs. https://mobsf.github.io/docs/#/running
I do not see any issue with `STATIC_ROOT = os.path.join(BASE_DIR, 'static')`

**Comment by XmTX1994** [comment]
Oh, I used "python manage.py runserver" to run mobsf. When I am using setup.bat and run.bat, it works well.

**Comment by ajinabraham** [comment]
Closing this.

**Pull request closed without merging**
