### PR TITLE
Prebuilt dex-enabled yara-python, improved setup script, Dockerfile, travis etc.

### PR DESCRIPTION
**Pull request by ajinabraham**
### Describe the Pull Request

```
* Bundle pre built dex enabled yara-python wheels for windows, mac and linux
* Improve setup scripts
* tox optimizations, lint now works on windows as well.
* Optimized travis.yml and Dockerfile
* Now we test MobSF on Python 3.6-3.8
(3.8 is not supported on Windows and Mac)
```

### Checklist for PR

- [x] Run MobSF unit tests and lint `tox -e lint,test`.
- [x] Tested Working on Linux, Mac, Windows, and Docker
- [x] Make sure build is passing on your PR. [Build Status](https://travis-ci.com/MobSF/Mobile-Security-Framework-MobSF/pull_requests)

### Additional Comments (if any)

```
DESCRIBE HERE
```

### CODE REVIEW

**Comment by ajinabraham** [comment]
Good Catch @superpoussin22

**Comment by superpoussin22** [comment]
MacOS and Docker are ok for me

**Comment by superpoussin22** [comment]
codacy sounds blocked ?

**Comment by ajinabraham** [comment]
@superpoussin22 It was not enabled for this branch. Just did that now.

**Comment by ajinabraham** [comment]
Also I will probably remove Codacy now that we have Sonarcloud and LGTM

**Pull request merged**
