### PR TITLE
update jadx to 1.3.4

### PR DESCRIPTION
**Pull request by superpoussin22**
### Describe the Pull Request

```
Update Jadx to latest version 1.3.5
update requirements 
```

### Checklist for PR

- [X] Run MobSF unit tests and lint `tox -e lint,test`
- [X] Tested Working on Linux, Mac, Windows, and Docker
- [X] Add unit test for any new Web API (Refer: `StaticAnalyzer/tests.py`)
- [X] Make sure tests are passing on your PR [MobSF tests](https://github.com/MobSF/Mobile-Security-Framework-MobSF/actions)

### Additional Comments (if any)

```
until we find a better way for updating
```

### CODE REVIEW

**Comment by ajinabraham** [comment]
@superpoussin22 Any ideas why the tests are filing. Decompiling is working fine?

**Comment by superpoussin22** [comment]
> @superpoussin22 Any ideas why the tests are filing. Decompiling is working fine?

don see such issue on my side :( really strange

**Comment by superpoussin22** [comment]
@ajinabraham if you can review this PR :)

**Review by ajinabraham — APPROVED** [review]
Ty, @superpoussin22

**Pull request merged**
